<a href="https://colab.research.google.com/github/estrickler1/CSPMA4413/blob/main/StricklerEthan_CPSMA4413_Project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Group Project 4:

The authors of this code 

Chiran Rayamajhi

Bigyan Sharma

Ethan Strickler 

Watan Chadhaury.

In [30]:
import math as m
import numpy as np


def Swap(Matrix, Row1, Row2):                                                     #swapping rows
  Matrix2 = []

  for i in range(len(Matrix)):

    if i == Row1:
      Matrix2.append(Matrix[Row2,:])

    elif i == Row2:
      Matrix2.append(Matrix[Row1,:])

    else:
      Matrix2.append(Matrix[i,:])

  return np.array(Matrix2)


def Add(Matrix, Row, ChangingRow):                                                    #Adding rows                             
  NewRow = Matrix[Row,:] + Matrix[ChangingRow,:]
  Matrix2 = []

  for i in range(len(Matrix)):

    if i == ChangingRow:
      Matrix2.append(Matrix[NewRow,:])

    else:
      Matrix2.append(Matrix[i,:])

    return np.array(Matrix2)


def Multiply(Matrix, Row, Value):                                                    #Multiplying by a constant
  NewRow = Matrix[Row,:] * Value
  Matrix2 = []

  for i in range(len(Matrix)):

    if i == Row:
      Matrix2.append(NewRow)

    else:
      Matrix2.append(Matrix[i,:])

  return np.array(Matrix2)

//Algorithm for solving the system of equations using Guass Jordan elimation method
1. First we need to start the solution.
2. Then ,read the number of unknown matrix denoted by: matrix  
3. Then again, read the Augumented Matrix (A) 
4. Transform the  required Augumented Matrix (A) to the Diagonal Matrix by using  Row Operations. 
5. Obtain the solution by making all Diagonal elements to 1. 
6. Dipslay the result of the required matrix.
7. Stop the solution. 

In [31]:
A = np.array([[2,3,1],[2,0,2]])

In [32]:
Add(A,0,1)

array([[2, 3, 1]])

In [33]:
Swap(A,0,1)

array([[2, 0, 2],
       [2, 3, 1]])

In [34]:
Multiply(A,1,3)

array([[2, 3, 1],
       [6, 0, 6]])

In [35]:
def LeadingOne(Matrix,Row,Column):
  Matrix2 =[]
  for i in range(len(Matrix)):
    if i != Row:
      Matrix2.append(Matrix[i,:])
    else:
      Matrix2.append(1/Matrix[Row,Column]*Matrix[Row,:])
  return np.array(Matrix2)

In [36]:
def AddMultiply(Matrix, ChangingRow, Row, Value):
  NewRow = Matrix[ChangingRow,:]+Value*Matrix[Row,:]
  Matrix2 = []
  for i in range(len(Matrix)):
    if i != ChangingRow:
      Matrix2.append(Matrix[i,:])
    else:
      Matrix2.append(NewRow)
  return np.array(Matrix2)

In [37]:
def GaussJordan(Matrix):                                                              #performing Gauss-Jordan process on leading one
  Matrix2 = Matrix
  for Pivot in range(len(Matrix)):
    Matrix2 = LeadingOne(Matrix2,Pivot,Pivot)
    for Column in range(0,Pivot):
      Matrix2 = AddMultiply(Matrix2,Column,Pivot,-Matrix2[Column,Pivot])
    for Column in range(Pivot+1,len(Matrix)):
      Matrix2 = AddMultiply(Matrix2,Column,Pivot,-Matrix2[Column,Pivot])
  return Matrix2

In [38]:
GaussJordan(A)

array([[ 1.        ,  0.        ,  1.        ],
       [-0.        ,  1.        , -0.33333333]])

 now for 3x4 matrix
 

In [39]:
B = np.array([[1,0,0,1],[0,1,2,3],[2,0,4,3]])

In [40]:
B = AddMultiply(B,1,0,-2)
B

array([[ 1,  0,  0,  1],
       [-2,  1,  2,  1],
       [ 2,  0,  4,  3]])

In [41]:
B = AddMultiply(B,0,1,2)
B

array([[-3,  2,  4,  3],
       [-2,  1,  2,  1],
       [ 2,  0,  4,  3]])

Swapping


In [42]:
Swap(B,0,1)

array([[-2,  1,  2,  1],
       [-3,  2,  4,  3],
       [ 2,  0,  4,  3]])

Multiply


In [43]:
Multiply(B,1,2)

array([[-3,  2,  4,  3],
       [-4,  2,  4,  2],
       [ 2,  0,  4,  3]])

In [44]:
c = np.array([[1,-2,2],[2,-4,4]])

In [45]:
GaussJordan(c)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in multiply
  import sys


array([[nan, nan, nan],
       [nan, nan, nan]])

The prior matrix does not work. This is because the martix had infinitly many solutions. To fix the algorithm to run properly, there could be an if statement. This statement would be placed after the for loops, and state that if an entire row has zeros, then return infinite solutions. However, the algorithm works as long as there is only one unique solution. 